/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : addresses
 #	author : miyako
 #	2017/05/22
 #
 # --------------------------------------------------------------------------------*/



// --- addresses
void IP_ADDRESS_LIST(sLONG_PTR *pResult, PackagePtr pParams);
